openapi: 3.1.0
info:
  title: wex
  version: '1.0'
paths:
  /storeTransaction:
    post:
      summary: ''
      operationId: post-storeTransaction
      responses:
        '200':
          $ref: '#/components/responses/storeTransactionResponse'
        '400':
          $ref: '#/components/responses/errorResponse'
        '500':
          $ref: '#/components/responses/errorResponse'
      description: ''
      requestBody:
        $ref: '#/components/requestBodies/storeTransactionRequest'
  /getTransaction:
    post:
      summary: ''
      operationId: post-getTransaction
      responses:
        '200':
          $ref: '#/components/responses/getTransactionResponse'
        '400':
          $ref: '#/components/responses/errorResponse'
        '500':
          $ref: '#/components/responses/errorResponse'
      requestBody:
        $ref: '#/components/requestBodies/getTransactionRequest'
components:
  schemas:
    Transaction:
      title: Transaction
      type: object
      properties:
        Id:
          type: string
        description:
          type: string
          minLength: 1
          maxLength: 50
        transactionDate:
          type: string
          format: date
        purchaseAmountUSD:
          type: number
          minimum: 0
      required:
        - Id
        - description
        - transactionDate
        - purchaseAmountUSD
  requestBodies:
    storeTransactionRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
                minLength: 1
                maxLength: 50
              transactionDate:
                type: string
                format: date
              purchaseAmountUSD:
                type: number
                minimum: 0
            required:
              - description
              - transactionDate
              - purchaseAmountUSD
    getTransactionRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              Id:
                type: string
              currency:
                type: string
            required:
              - Id
              - currency
  responses:
    errorResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
            required:
              - description
        application/xml:
          schema:
            $ref: '#/components/schemas/Transaction'
    storeTransactionResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transaction'
    getTransactionResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              description:
                type: string
                minLength: 1
                maxLength: 50
              transactionDate:
                type: string
                format: date
              purchaseAmountUSD:
                type: number
              exchangeRate:
                type: number
              purchaseAmountTargetCurrency:
                type: number
            required:
              - id
              - description
              - transactionDate
              - purchaseAmountUSD
              - exchangeRate
              - purchaseAmountTargetCurrency
