openapi: 3.1.0
info:
  title: wex
  version: '1.0'
paths:
  /storeTransaction:
    post:
      summary: ''
      operationId: post-storeTransaction
      responses:
        '200':
          $ref: '#/components/responses/storeTransactionResponse'
        '400':
          $ref: '#/components/responses/errorResponse'
        '500':
          $ref: '#/components/responses/errorResponse'
      description: ''
      requestBody:
        $ref: '#/components/requestBodies/storeTransactionRequest'
  /getTransaction:
    post:
      summary: ''
      operationId: post-getTransaction
      responses:
        '200':
          $ref: '#/components/responses/getTransactionResponse'
        '400':
          $ref: '#/components/responses/errorResponse'
        '500':
          $ref: '#/components/responses/errorResponse'
      requestBody:
        $ref: '#/components/requestBodies/getTransactionRequest'
components:
  schemas:
    Transaction:
      title: Transaction
      type: object
      properties:
        ID:
          type: string
        description:
          type: string
          minLength: 1
        transactionDate:
          type: string
          format: date-time
        purchaseAmount:
          type: number
          minimum: 0
      required:
        - ID
        - description
        - transactionDate
        - purchaseAmount
  requestBodies:
    storeTransactionRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
                minLength: 1
              transactionDate:
                type: string
                format: date-time
              purchaseAmount:
                type: number
                minimum: 0
            required:
              - description
              - transactionDate
              - purchaseAmount
    getTransactionRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              ID:
                type: string
            required:
              - ID
  responses:
    errorResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
            required:
              - description
        application/xml:
          schema:
            $ref: '#/components/schemas/Transaction'
    storeTransactionResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transaction'
    getTransactionResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transaction'
