// Package wex provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package wex

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Transaction defines model for Transaction.
type Transaction struct {
	ID              string  `json:"ID"`
	Description     string  `json:"description"`
	PurchaseAmount  float32 `json:"purchaseAmount"`
	TransactionDate string  `json:"transactionDate"`
}

// ErrorResponse defines model for errorResponse.
type ErrorResponse struct {
	Description string `json:"description"`
}

// GetTransactionResponse defines model for getTransactionResponse.
type GetTransactionResponse = Transaction

// StoreTransactionResponse defines model for storeTransactionResponse.
type StoreTransactionResponse = Transaction

// GetTransactionRequest defines model for getTransactionRequest.
type GetTransactionRequest struct {
	ID string `json:"ID"`
}

// StoreTransactionRequest defines model for storeTransactionRequest.
type StoreTransactionRequest struct {
	Description     string  `json:"description"`
	PurchaseAmount  float32 `json:"purchaseAmount"`
	TransactionDate string  `json:"transactionDate"`
}

// PostGetTransactionJSONBody defines parameters for PostGetTransaction.
type PostGetTransactionJSONBody struct {
	ID string `json:"ID"`
}

// PostStoreTransactionJSONBody defines parameters for PostStoreTransaction.
type PostStoreTransactionJSONBody struct {
	Description     string  `json:"description"`
	PurchaseAmount  float32 `json:"purchaseAmount"`
	TransactionDate string  `json:"transactionDate"`
}

// PostGetTransactionJSONRequestBody defines body for PostGetTransaction for application/json ContentType.
type PostGetTransactionJSONRequestBody PostGetTransactionJSONBody

// PostStoreTransactionJSONRequestBody defines body for PostStoreTransaction for application/json ContentType.
type PostStoreTransactionJSONRequestBody PostStoreTransactionJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostGetTransactionWithBody request with any body
	PostGetTransactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostGetTransaction(ctx context.Context, body PostGetTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostStoreTransactionWithBody request with any body
	PostStoreTransactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostStoreTransaction(ctx context.Context, body PostStoreTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostGetTransactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostGetTransactionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostGetTransaction(ctx context.Context, body PostGetTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostGetTransactionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostStoreTransactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostStoreTransactionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostStoreTransaction(ctx context.Context, body PostStoreTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostStoreTransactionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostGetTransactionRequest calls the generic PostGetTransaction builder with application/json body
func NewPostGetTransactionRequest(server string, body PostGetTransactionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostGetTransactionRequestWithBody(server, "application/json", bodyReader)
}

// NewPostGetTransactionRequestWithBody generates requests for PostGetTransaction with any type of body
func NewPostGetTransactionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/getTransaction")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostStoreTransactionRequest calls the generic PostStoreTransaction builder with application/json body
func NewPostStoreTransactionRequest(server string, body PostStoreTransactionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostStoreTransactionRequestWithBody(server, "application/json", bodyReader)
}

// NewPostStoreTransactionRequestWithBody generates requests for PostStoreTransaction with any type of body
func NewPostStoreTransactionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/storeTransaction")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostGetTransactionWithBodyWithResponse request with any body
	PostGetTransactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostGetTransactionResponse, error)

	PostGetTransactionWithResponse(ctx context.Context, body PostGetTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostGetTransactionResponse, error)

	// PostStoreTransactionWithBodyWithResponse request with any body
	PostStoreTransactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostStoreTransactionResponse, error)

	PostStoreTransactionWithResponse(ctx context.Context, body PostStoreTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostStoreTransactionResponse, error)
}

type PostGetTransactionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetTransactionResponse
	JSON400      *ErrorResponse
	XML400       *ErrorResponse
	JSON500      *ErrorResponse
	XML500       *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostGetTransactionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostGetTransactionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostStoreTransactionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StoreTransactionResponse
	JSON400      *ErrorResponse
	XML400       *ErrorResponse
	JSON500      *ErrorResponse
	XML500       *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostStoreTransactionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostStoreTransactionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostGetTransactionWithBodyWithResponse request with arbitrary body returning *PostGetTransactionResponse
func (c *ClientWithResponses) PostGetTransactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostGetTransactionResponse, error) {
	rsp, err := c.PostGetTransactionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostGetTransactionResponse(rsp)
}

func (c *ClientWithResponses) PostGetTransactionWithResponse(ctx context.Context, body PostGetTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostGetTransactionResponse, error) {
	rsp, err := c.PostGetTransaction(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostGetTransactionResponse(rsp)
}

// PostStoreTransactionWithBodyWithResponse request with arbitrary body returning *PostStoreTransactionResponse
func (c *ClientWithResponses) PostStoreTransactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostStoreTransactionResponse, error) {
	rsp, err := c.PostStoreTransactionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostStoreTransactionResponse(rsp)
}

func (c *ClientWithResponses) PostStoreTransactionWithResponse(ctx context.Context, body PostStoreTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostStoreTransactionResponse, error) {
	rsp, err := c.PostStoreTransaction(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostStoreTransactionResponse(rsp)
}

// ParsePostGetTransactionResponse parses an HTTP response from a PostGetTransactionWithResponse call
func ParsePostGetTransactionResponse(rsp *http.Response) (*PostGetTransactionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostGetTransactionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetTransactionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "xml") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := xml.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.XML400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "xml") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := xml.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.XML500 = &dest

	}

	return response, nil
}

// ParsePostStoreTransactionResponse parses an HTTP response from a PostStoreTransactionWithResponse call
func ParsePostStoreTransactionResponse(rsp *http.Response) (*PostStoreTransactionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostStoreTransactionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StoreTransactionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "xml") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := xml.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.XML400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "xml") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := xml.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.XML500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /getTransaction)
	PostGetTransaction(ctx echo.Context) error

	// (POST /storeTransaction)
	PostStoreTransaction(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostGetTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) PostGetTransaction(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostGetTransaction(ctx)
	return err
}

// PostStoreTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) PostStoreTransaction(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostStoreTransaction(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/getTransaction", wrapper.PostGetTransaction)
	router.POST(baseURL+"/storeTransaction", wrapper.PostStoreTransaction)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RVT2/bPgz9Kj/wt6NQeet20W1DhiG3odut6EF12FqFLWoSvaUI/N0Hyi5qJ3ZXGN16",
	"CQzqkXx8/JMDlNQE8ug5gTlAxB8tJv5EO4fZcIv8PVqfbMmO/EX/LA8leUafP20ItSutAPRdIi+2VFbY",
	"WPkKkQJGHuJtN/LL9wHBQOLo/C10ncqJXcQdmEvBXKkHDF3fYcnQdYJKTBFflM8OUxldEOwMMQWhjWVl",
	"E35sqO2jDxDfNtcYBcKPfDaW8c/1jXOeup/knNUih0yBfOrrwBgpXgyWv6bHE4XMsFSTzPumniZ+E/EG",
	"DPyvH0dQ969Jj3oMudgJL/i8t02o8b8HCaQNx5O6QooXZnQ6ra/NSUj1vhJ67P68RVWvsi/bDag1S+O4",
	"lqjjMmdWSYHzN5RZDA6/cA8KfmJMvY5vzwrhTQG9DQ4MnJ+JSUGwXGWx9HT4sprU3yXRNPd2uwMDXynx",
	"lylWjY7u/VLHJ3dZzx/l45PwriiWww04vbA1nYL3z3Gfnp1OwYcVXrkJ+nhbnhbx2zF6hYxL/yarhFxc",
	"9n8tpew4RpleMJcHaGMNBirmYLSuqbR1RYnNeVEU0F11vwMAAP//KIU03QEIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
